export interface DevCategoryConfig {
  key: string;
  label: string;
  description: string;
}

export interface DevSourceConfig {
  key: string;
  label: string;
  description: string;
  categoryKey: string;
  table: string;
  orderField: string;
  fixedValues?: Record<string, unknown>;
  summaryFields?: string[];
  titleField?: string;
  defaultRecord: Record<string, unknown>;
}

export const ASSET_WORKBENCH_SOURCE_KEYS = [
  "terrain_assets",
  "structure_assets",
  "background_assets",
  "effect_assets",
  "character_assets",
  "monster_assets",
  "audio_entries",
] as const;

export const DEV_PANEL_CATEGORIES: DevCategoryConfig[] = [
  {
    key: "creatures",
    label: "Creatures",
    description: "Monsters, NPCs, factions, and creature-facing assets.",
  },
  {
    key: "worlds",
    label: "Worlds",
    description: "Maps, spawn pools, world definitions, and overrides.",
  },
  {
    key: "story",
    label: "Story",
    description: "Dialogues, lore, legends, narrative files, and audio cues.",
  },
  {
    key: "progression",
    label: "Progression",
    description: "Items, equipment, and progression-facing content.",
  },
  {
    key: "players",
    label: "Players",
    description: "Players, legends, characters, saves, and system records.",
  },
  {
    key: "assets",
    label: "Assets",
    description: "Backgrounds, effects, character parts, and general asset registry entries.",
  },
];

export const DEV_PANEL_SOURCES: DevSourceConfig[] = [
  {
    key: "monsters",
    label: "Monster Data",
    description: "Core combat monsters and their stats.",
    categoryKey: "creatures",
    table: "monsters",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["biome", "rarity", "description", "image_url"],
    defaultRecord: {
      name: "New Monster",
      level: 1,
      base_hp: 50,
      base_attack: 10,
      base_defense: 5,
      speed: 5,
      skill_id: 111111111,
      type: "beast",
      biome: "forest",
      rarity: "common",
      description: "",
      image_url: "",
    },
  },
  {
    key: "monster_assets",
    label: "Monster Images",
    description: "Art assets and media for monsters.",
    categoryKey: "creatures",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "monster",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags"],
    defaultRecord: {
      category: "asset",
      subcategory: "monster",
      content_kind: "image",
      title: "New Monster Portrait",
      slug: "new-monster-portrait",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["monster"],
      metadata_json: {},
      is_active: true,
    },
  },
  {
    key: "npcs",
    label: "NPC Data",
    description: "Named NPCs and their world roles.",
    categoryKey: "creatures",
    table: "npcs",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["role", "region", "personality", "description"],
    defaultRecord: {
      name: "New NPC",
      role: "merchant",
      region: "",
      personality: "",
      description: "",
    },
  },
  {
    key: "factions",
    label: "Factions",
    description: "Groups, organizations, and ideological blocs.",
    categoryKey: "creatures",
    table: "factions",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["type", "ideology", "description"],
    defaultRecord: {
      name: "New Faction",
      type: "guild",
      ideology: "",
      description: "",
    },
  },
  {
    key: "maps",
    label: "Map Records",
    description: "Regions and local map records.",
    categoryKey: "worlds",
    table: "maps",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["biome", "danger_level", "description", "image_url"],
    defaultRecord: {
      name: "New Region",
      danger_level: 1,
      biome: "forest",
      description: "",
      image_url: "",
    },
  },
  {
    key: "spawn_points",
    label: "Spawn Pools",
    description: "Monster pools and spawn rates per map.",
    categoryKey: "worlds",
    table: "spawn_points",
    orderField: "created_at",
    titleField: "map_id",
    summaryFields: ["monster_pool", "spawn_rate"],
    defaultRecord: {
      map_id: "",
      monster_pool: [],
      spawn_rate: 0.5,
    },
  },
  {
    key: "world_definitions",
    label: "World Definitions",
    description: "Canonical world definitions and their stored metadata.",
    categoryKey: "worlds",
    table: "world_definitions",
    orderField: "updated_at",
    titleField: "world_name",
    summaryFields: ["generation_mode", "world_preset", "custom_biomes", "custom_monsters"],
    defaultRecord: {
      character_id: "",
      world_seed: 500000000,
      generation_mode: "procedural",
      world_name: "New World",
      world_preset: "balanced",
      custom_biomes: [],
      custom_monsters: [],
      metadata_json: {},
      definition_json: {},
      source_lore: "",
      definition_version: 1,
    },
  },
  {
    key: "world_overrides",
    label: "World Overrides",
    description: "Manual patches applied on top of canonical worlds.",
    categoryKey: "worlds",
    table: "world_overrides",
    orderField: "updated_at",
    titleField: "override_type",
    summaryFields: ["scope_type", "scope_ref", "payload_json"],
    defaultRecord: {
      world_definition_id: "",
      override_type: "patch_region",
      scope_type: "region",
      scope_ref: "",
      payload_json: {},
    },
  },
  {
    key: "dialogues",
    label: "Dialogues",
    description: "Dialogue text, NPC lines, and message fragments.",
    categoryKey: "story",
    table: "dialogues",
    orderField: "created_at",
    titleField: "npc_name",
    summaryFields: ["dialogue_text"],
    defaultRecord: {
      npc_name: "Narrator",
      dialogue_text: "",
    },
  },
  {
    key: "lore_snippets",
    label: "Lore Snippets",
    description: "World lore and story fragments used during exploration.",
    categoryKey: "story",
    table: "lore_snippets",
    orderField: "created_at",
    titleField: "title",
    summaryFields: ["biome", "rarity", "content"],
    defaultRecord: {
      title: "Ancient Fragment",
      content: "",
      rarity: "common",
      biome: "",
      world_definition_id: null,
    },
  },
  {
    key: "story_files",
    label: "Story Files",
    description: "Long-form story text and world-linked narrative documents.",
    categoryKey: "story",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "story",
      content_kind: "text",
    },
    summaryFields: ["summary", "body_text", "world_definition_id"],
    defaultRecord: {
      category: "story",
      subcategory: "world-lore",
      content_kind: "text",
      title: "New Story File",
      slug: "new-story-file",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "text/plain",
      tags: ["story"],
      metadata_json: {},
      world_definition_id: null,
      is_active: true,
    },
  },
  {
    key: "audio_entries",
    label: "Audio Files",
    description: "Music cues, ambience, voice, and sound effects.",
    categoryKey: "story",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "audio",
      content_kind: "audio",
    },
    summaryFields: ["summary", "file_url", "mime_type", "tags"],
    defaultRecord: {
      category: "audio",
      subcategory: "ambient",
      content_kind: "audio",
      title: "New Audio Cue",
      slug: "new-audio-cue",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "audio/mpeg",
      tags: ["audio"],
      metadata_json: {},
      world_definition_id: null,
      is_active: true,
    },
  },
  {
    key: "items",
    label: "Items",
    description: "Consumables, keys, quest items, and materials.",
    categoryKey: "progression",
    table: "items",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["type", "rarity", "description", "image_url"],
    defaultRecord: {
      name: "New Item",
      type: "consumable",
      stat_bonus: {},
      image_url: "",
      rarity: "common",
      description: "",
    },
  },
  {
    key: "equipment",
    label: "Equipment",
    description: "Wearable gear and stat-bearing equipment.",
    categoryKey: "progression",
    table: "equipment",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["slot", "rarity", "description", "image_url"],
    defaultRecord: {
      name: "New Equipment",
      slot: "weapon",
      attack_bonus: 0,
      defense_bonus: 0,
      speed_bonus: 0,
      hp_bonus: 0,
      image_url: "",
      rarity: "common",
      description: "",
    },
  },
  {
    key: "legends",
    label: "Legend Records",
    description: "Persistent history written into the world.",
    categoryKey: "progression",
    table: "legends",
    orderField: "created_at",
    titleField: "player_name",
    summaryFields: ["region_name", "event_text", "turn_number"],
    defaultRecord: {
      world_id: "",
      player_name: "Hero",
      event_text: "",
      turn_number: 0,
      region_name: "",
    },
  },
  {
    key: "players",
    label: "Players",
    description: "Player profiles used by auth and persistence.",
    categoryKey: "players",
    table: "players",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["email", "user_id"],
    defaultRecord: {
      name: "New Player",
      email: "",
      user_id: null,
    },
  },
  {
    key: "characters",
    label: "Characters",
    description: "Legends, their stats, and their signature skill.",
    categoryKey: "players",
    table: "characters",
    orderField: "created_at",
    titleField: "name",
    summaryFields: ["player_id", "level", "skill_main"],
    defaultRecord: {
      player_id: "",
      name: "New Character",
      level: 1,
      hp: 100,
      max_hp: 100,
      mana: 50,
      max_mana: 50,
      attack: 10,
      defense: 5,
      speed: 10,
      skill_main: 111111111,
    },
  },
  {
    key: "player_states",
    label: "Player States",
    description: "Live save-state snapshots and traversal progress.",
    categoryKey: "players",
    table: "player_states",
    orderField: "updated_at",
    titleField: "character_name",
    summaryFields: ["phase", "world_seed", "current_map", "last_event"],
    defaultRecord: {
      character_id: "",
      current_region: 0,
      current_map: "",
      hp: 100,
      mana: 50,
      max_hp: 100,
      max_mana: 50,
      exp: 0,
      level: 1,
      gold: 0,
      inventory_json: [],
      equipment_json: {
        weapon: null,
        armor: null,
        accessory: null,
      },
      world_seed: 0,
      last_event: "",
      character_name: "Hero",
      last_action_log: "",
      phase: "IDLE",
    },
  },
  {
    key: "terrain_assets",
    label: "Terrain Assets",
    description: "Geography, terrain fragments, landmasses, cliffs, rivers, and biome paint layers.",
    categoryKey: "assets",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "terrain",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags", "metadata_json"],
    defaultRecord: {
      category: "asset",
      subcategory: "terrain",
      content_kind: "image",
      title: "New Terrain Asset",
      slug: "new-terrain-asset",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["terrain", "geography"],
      metadata_json: {
        terrainType: "plains",
        biome: "forest",
        renderLayer: "midground",
        intendedUse: "world-geography",
        tileable: false,
        paletteHints: [],
      },
      is_active: true,
    },
  },
  {
    key: "structure_assets",
    label: "Structure Assets",
    description: "Cities, ruins, bridges, castles, settlements, and interior/exterior structure art.",
    categoryKey: "assets",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "structure",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags", "metadata_json"],
    defaultRecord: {
      category: "asset",
      subcategory: "structure",
      content_kind: "image",
      title: "New Structure Asset",
      slug: "new-structure-asset",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["structure", "settlement"],
      metadata_json: {
        structureType: "city",
        biome: "",
        renderLayer: "foreground",
        intendedUse: "regional-map",
        tileable: false,
        paletteHints: [],
      },
      is_active: true,
    },
  },
  {
    key: "background_assets",
    label: "Background Assets",
    description: "Scene backdrops and environmental image assets.",
    categoryKey: "assets",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "background",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags"],
    defaultRecord: {
      category: "asset",
      subcategory: "background",
      content_kind: "image",
      title: "New Background",
      slug: "new-background",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["background"],
      metadata_json: {},
      is_active: true,
    },
  },
  {
    key: "effect_assets",
    label: "Effect Assets",
    description: "VFX, overlays, sigils, and animated image resources.",
    categoryKey: "assets",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "effect",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags"],
    defaultRecord: {
      category: "asset",
      subcategory: "effect",
      content_kind: "image",
      title: "New Effect",
      slug: "new-effect",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["effect"],
      metadata_json: {},
      is_active: true,
    },
  },
  {
    key: "character_assets",
    label: "Character Parts",
    description: "Heads, faces, hairstyles, hair colors, and other hero parts.",
    categoryKey: "assets",
    table: "content_entries",
    orderField: "updated_at",
    titleField: "title",
    fixedValues: {
      category: "asset",
      subcategory: "character-part",
      content_kind: "image",
    },
    summaryFields: ["summary", "file_url", "tags"],
    defaultRecord: {
      category: "asset",
      subcategory: "character-part",
      content_kind: "image",
      title: "New Character Part",
      slug: "new-character-part",
      summary: "",
      body_text: "",
      file_url: "",
      preview_url: "",
      mime_type: "image/png",
      tags: ["character", "head"],
      metadata_json: {
        partType: "head",
      },
      is_active: true,
    },
  },
];

export function getDevCategoryConfig(categoryKey: string) {
  return DEV_PANEL_CATEGORIES.find((category) => category.key === categoryKey) || null;
}

export function getDevSourceConfig(sourceKey: string) {
  return DEV_PANEL_SOURCES.find((source) => source.key === sourceKey) || null;
}

export function getAssetWorkbenchSourceConfigs() {
  return ASSET_WORKBENCH_SOURCE_KEYS.map((key) => getDevSourceConfig(key)).filter(
    (source): source is DevSourceConfig => !!source,
  );
}
